// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4A8PlqkJ9Ixw0kywyV6L4Xm5Of_qZT4',
    appId: '1:619938283063:web:860a37070155eb1d2b89b2',
    messagingSenderId: '619938283063',
    projectId: 'quizimen-6004e',
    authDomain: 'quizimen-6004e.firebaseapp.com',
    databaseURL: 'https://quizimen-6004e-default-rtdb.firebaseio.com',
    storageBucket: 'quizimen-6004e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_avbRRZ19b9SZ5Dfx-IjW2639L0EqgQg',
    appId: '1:619938283063:android:6528fe6d44554fa22b89b2',
    messagingSenderId: '619938283063',
    projectId: 'quizimen-6004e',
    databaseURL: 'https://quizimen-6004e-default-rtdb.firebaseio.com',
    storageBucket: 'quizimen-6004e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQVHi54opAXzCW67pDBZVhoFbYAEO6Lg',
    appId: '1:619938283063:ios:e79849006b38a56e2b89b2',
    messagingSenderId: '619938283063',
    projectId: 'quizimen-6004e',
    databaseURL: 'https://quizimen-6004e-default-rtdb.firebaseio.com',
    storageBucket: 'quizimen-6004e.appspot.com',
    iosClientId: '619938283063-p4uoff7e0ornlnnldt7j4hgm4dsh8l1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQVHi54opAXzCW67pDBZVhoFbYAEO6Lg',
    appId: '1:619938283063:ios:991dd1483a7bf70f2b89b2',
    messagingSenderId: '619938283063',
    projectId: 'quizimen-6004e',
    databaseURL: 'https://quizimen-6004e-default-rtdb.firebaseio.com',
    storageBucket: 'quizimen-6004e.appspot.com',
    iosClientId: '619938283063-9pli1m9r1ls0e9pfj34fffsedpu4fkbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminQuiz.RunnerTests',
  );
}
